Repository smakosh/CRA-boilerplate, pull requests merged in 2020-11, with the labels that each got.

#8 chore: refactored code
  package.json
  src/config/index.js
  src/features/auth/hooks/useDispatchUser.js
  src/features/auth/hooks/useFetchUser.js
  src/features/auth/hooks/useUser.js
  src/features/auth/modules/Login/index.jsx
  src/features/auth/modules/Register/index.jsx
  src/features/auth/providers/UserProvider.js
  src/features/auth/reducers/UserReducer.js
  src/features/dashboard/modules/Dashboard/index.jsx
  src/helpers/setAuthToken.js
  src/helpers/toBase64.js
  src/routes/App.jsx
  src/routes/Authenticated.jsx
  src/routes/Unauthenticated.jsx
  src/ui/components/Card/index.js
  src/ui/components/ErrorField/index.js
  src/ui/components/Header/index.jsx
  src/ui/theme/theme.js
  yarn.lock
Labels: enhancement

#10 chore: upgraded CRA
  .env
  .eslintcache
  package.json
  src/features/auth/modules/Login/index.tsx
  src/features/auth/modules/Register/index.tsx
  src/features/dashboard/actions.ts
  src/helpers/setAuthToken.ts
  src/react-app-env.d.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#11 docs: highlight the TS version
  README.md
Labels: documentation

#13 docs: update docs, include a license and remove cross env
  .env
  .env.development.template
  .env.production.template
  LICENSE.md
  README.md
  package.json
  yarn.lock
Labels: documentation, enhancement

#15 Refact: add localStorage helper.
  src/features/auth/actions.js
  src/features/auth/hooks/useFetchUser.js
  src/features/auth/providers/UserProvider.js
  src/helpers/storage.js
Labels: enhancement
